#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/thorsh"

cmd="usage"

add_function servers "List all of the servers"
function servers() {
    $DIR/server list
}

add_function names server "List all of names of a server"
function names() {
    ip=$($DIR/server ip ${server})
    if [[ -z "$ip" ]] ; then
        echo $server not found!
        exit 1
    fi
    $DIR/dns list | awk "/$($DIR/server ip ${server})/ {print \$3}"
}

add_function create_server name "Create a new server and bootstrap it"
function create_server() {
    ip=$($DIR/server ip ${name})
    if [[ -z "$ip" ]]; then
        echo Creating ${name}
        $DIR/server add ${name}
        echo Waiting 5 seconds for server to come on line
        sleep 5
    else
        echo ${name} already existing
    fi
    
    $DIR/dns add_name ${name} $($DIR/server ip ${name})
    bootstrap
}

add_function nuke_server server "Removes the server and all dns records pointing to it"
function nuke_server() {
    echo Nuking ${server}

    for name in $(names); do
        $DIR/dns rm_name ${name}
    done

    $DIR/server rm_server ${server}
}


add_function bootstrap name "Bootstrap a remote server"
function bootstrap() {
    ip=$($DIR/server ip ${name})
    (
        cd $DIR
        bash thorsh inline bootstrap
        bash thorsh inline dns
        scp bootstrap.inlined root@${ip}:/root/bootstrap
        ssh root@${ip} bash bootstrap bootstrap
        update_deployer
    )
}

add_function update_deployer name "Update the deployer on a remote server"
function update_deployer {
    (
        cd $DIR
        ip=$($DIR/server ip ${name})
        scp deployer post-receive root@${ip}:/root/
        ssh root@${ip} "chmod +x deployer post-receive;mv deployer post-receive ~deploy"
    )
}

thorsh "$@"
